### ISSUE TITLE
Groups and members

### ISSUE THREAD

**Issue by lukagulin** [pa1511/TestGenerator#11]
Need to decide how to handle relations beetwen groups and corresponding member. Now it is implemented both in group and member. That may cause problems while adding and removing members from group.
Solutions:
1) Leave as is
2) Remove one or the other

**Comment by pa1511** [comment]
If we remove one of the relations I suggest it is the one from member to group.
But, having a two way connection might be convenient.

**Comment by lukagulin** [comment]
I agree that is convenient, but I'd like find some clever way of implementing it.
