### ISSUE TITLE
Create database structure - feature request

### ISSUE THREAD

**Issue by pa1511** [pa1511/TestGenerator#4]
We will need to create a database to store all the necessary information. 
There already exists a connection to a H2 database so we now need to create the needed structure.
You can find information about the H2 database at: [link](http://www.h2database.com/)

**Comment by lukagulin** [comment]
Otprilike SQL stringovi, provjeri jel dobro:


CREATE TABLE Questions(ID int NOT NULL AUTO_INCREMENT, QuestionText varchar(1023), RelativeWeigth int, PRIMARY KEY (ID))
CREATE TABLE Answers(ID int NOT NULL AUTO_INCREMENT, AnswerText varchar(255), ParentID int, IsCorrect boolean PRIMARY KEY (ID))
//ima li uopće boolean?
//prilikom brisanja questiona brisat odgovore s tim IDom

CREATE TABLE QuestionDependancies(ParentQuestionID int, ChildAnswerID int)
// dodat da se ova tablica automatski osvježava kad se izbriše pitanje ili odgovor; deny orphan answers

CREATE TABLE QuestionsGroups(ID int NOT NULL AUTO_INCREMENT, GroupName varchar(255), PRIMARY KEY (ID))
CREATE TABLE QuestionGroupDependancies(ParentQuestionGroupID int, ChildGroupID int)
// dodat da se ova tablica automatski osvježava prilikom promjena u Questions i QuestionsGroups; allow orphan questions


CREATE TABLE People(ID int NOT NULL AUTO_INCREMENT, FirstName varchar(255) NOT NULL LastName varchar(255) NOT NULL, DateOfBirth date, UserUniqeIdentifier int, PrimaryGroupID int, PRIMARY KEY (ID))
//dodatni stupci tablice s opcionalnim podacima da useru bude lakše diferencirat među peoplsima. Možemo dodat još čisto da ima
//UserUniqeIdentifier nisan stavija constraint jer san ovo namjenia da bude neki user definirani broj. ali svakako stavit upozorenje ako isti postoji u bazi

CREATE TABLE PeopleGroups(ID int NOT NULL AUTO_INCREMENT, GroupName varchar(255), PRIMARY KEY (ID))
CREATE TABLE PeopleGroupDependancies(ParentPeopleGroupID int, ChildPeopleID int)
// dodat da se ova tablica automatski osvježava prilikom promjena u People i PeoplesGroups; allow orphan people

//-------------------------------------------------------------------------

//tablice za generirane testove, kasnije, još ne znamo točnu strukturu testova
